name: "Tests"
on:
  workflow_dispatch:
    inputs:
      test-filter:
        description: 'Optional jasmine filter expression'
        required: false
        default: ''

jobs:
  Test:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node_version: ['14', '16']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests 👩🏽‍💻
        run: |
          if [ -n "${{ inputs.test-filter }}" ]; then
            npm run test:unit -- --filter="${{ inputs.test-filter }}"
          else
            npm run test:unit
          fi
      - name: Run Spec Tests 👩🏽‍💻
        run: |
          if [ -n "${{ inputs.test-filter }}" ]; then
            npm run test:specs -- --filter="${{ inputs.test-filter }}"
          else
            npm run test:specs
          fi
      - name: Pack tarball 📦
        if: matrix.node_version == '14'
        run: |
          npm i -g npm@7.12.0
          npm pack
      - name: Upload tarball
        if: matrix.node_version == '14'
        uses: actions/upload-artifact@v4
        with:
          name: npm-tarball
          path: marked-*.tgz
          if-no-files-found: error
